@baseUrl = http://localhost:8000/api
@email=company@gmail.com
@password=1
@Auth_token=244|ygdCii7TkgEHjyyRmp8XZAt0Yt7iC8x8sjE7BQaI

### Company Login
POST  {{baseUrl}}/AdminLoginEmail/
Content-Type: application/json

{
"email": "{{email}}",
"password": "{{password}}"
}

###
###Company Create User
POST  {{baseUrl}}/CreateUser
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}

{
"name": "kebine eric Muna",
"email": "on@gmail.com",
"Ccode": "+250",
"phone": "0782389359",
"country":"Rwanda",
"password": "1"

}


###Create User and Assign With Card iyi niyo nyayo ikora neza
POST  {{baseUrl}}/CreateUserAssign
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}

{
"name":"kebine eric Muna",
"email":"on2@gmail.com",
"Ccode":"+250",
"phone":"7823893587",
"initCountry":"US",
"country":"Rwanda",
"password":"1",
"carduid":"TEALTD_7hEnj_1672352175"

}
###Edit User and Assign With Card iyi niyo nyayo ikora neza Auth User Register
POST  {{baseUrl}}/EditUserAssign
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}

{
"uid":"kebineericMuna_1674592764",
"name":"gogo",
"email":"on2@gmail.com",
"Ccode":"250",
"phone":"0789359",
"country":"Rwanda",
"initCountry":"initCountry",
"status":"test",
"password":"1",
"carduid":"TEALTD_lN7o8_1672352175"

}

### Add Balance

POST  {{baseUrl}}/AddBalance
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}

{
"uidUser":"kebineericMuna_1674592764",
"balance":"250",
"description":"Balance of User"


}
### EditBalance

POST  {{baseUrl}}/EditBalance
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}

{
"uidUser":"kebineericMuna_1674592764",
"balance":"-450",
"description":"Balance of User"


}
### Redeemmed Balance (Withdraw)
POST  {{baseUrl}}/RedeemBalance
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}

{
"uid":"kebineericMuna_1674592764",
"amount":"100",
"description":"descr"
}
### Redeemmed Bonus
POST  {{baseUrl}}/RedeemBonus
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}

{
"uid":"kebineericMuna_1674592764",
"amount":"300",
"description":"descr"
}

###
GET  http://localhost:8000/submit-form
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}

{
"Ccode":"250",
"phone":"0782389359"



}

###Company GEt Details of Card ID using number this will help me to assign user with new card
GET  {{baseUrl}}/GetNumberDetail
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}

{
"Ccode":"+250",
"phone":"0782389359"



}
###Company GEt Details of Card ID or to check if he reached target
GET  {{baseUrl}}/GetCardDetail
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}

{
"carduid":"TEALTD_7hEnj_1672352175"



}

### Get Balance and Bonus of User

GET  {{baseUrl}}/GetBalanceUser
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}

{
"uid":"kebineericMuna_1674160265"



}
### Get Balance and Bonus Hist

GET  {{baseUrl}}/GetBalanceHist
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}

{
"uid":"kebineericMuna_1668935593",
"LimitStart":0,
"LimitEnd":10,
"optionCase":"bonus"



}
### print card
GET  {{baseUrl}}/PrintCard
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}

###Company Create Card single card depricated
POST  {{baseUrl}}/CreateCard
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}

{
"numberQr": "kebine eric Muna"

}
###Company Create Multiple Card
POST  {{baseUrl}}/CreateMultipleCard
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}

{
"numberQr":3

}

###Company Assign Card to User /*uid of user*/
POST  {{baseUrl}}/AssignCard
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}

{
"Ccode": "+250",
"phone":"0782389359",
"carduid":"TEALTD_7hEnj_1672352175"



}
###Company Syncronous card Data

GET  {{baseUrl}}/CompanySyncCardDownload
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}

{
"versionCount":"0"

}


###Company Create Promotion
POST  {{baseUrl}}/CreatePromotionEvent
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}

{
"promoName":"Vita",
"promoMsg":"i will give you 300 nugura ibintu bya 1000$",
"reach":"1200",
"gain":"350",
"extended_date":"15-03-2023 12:00:0 to 24-03-2023 12:00:0",
"status":"On"

}

###Company GetAll Promotion
GET  {{baseUrl}}/GetAllPromotionEvent
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}


###Company Set Promotion status uid=//promotion ID
POST  {{baseUrl}}/SetPromotionEventStatus
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}

{
"uid":"Nyota_1672353378",
"status":"On"

}

### Company Make User Participate in Events:uid,reach,gain come from promotion
POST  {{baseUrl}}/ParticipateEvent
Content-Type: application/json
Authorization: Bearer {{Auth_token}}

{
"uid":"kivuBucket_1672353285",
"uidUser":"kebineericMuna_1674160265",
"inputData":"102",
"reach":"300",
"gain":"100"


}
### Edit ParticipateEditEvent this inputData is from InputData from participatedHist
POST  {{baseUrl}}/ParticipateEditEvent
Content-Type: application/json
Authorization: Bearer {{Auth_token}}

{
"uid":"kivuBucket_1672353285",
"uidUser":"kebineericMuna_1674160265",
"inputData":"30",
"reach":"300",
"gain":"200"


}


### Get All participateEvents

GET  {{baseUrl}}/GetAllParticipateEvent
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}

{
"uidUser":"kebineericMuna_1668935593",
"LimitStart":0,
"LimitEnd":10


}
### count all event participated
GET  {{baseUrl}}/CountParticipateEvent
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}

{
"uidUser":"kebineericMuna_1668935593"


}
### Get All  GetActiveParticipateEvents

GET  {{baseUrl}}/GetActiveParticipateEvent
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}

{
"uidUser":"kebineericMuna_1668935593",
"LimitStart":0,
"LimitEnd":10


}
### Get All GetReachedParticipateEvent

GET  {{baseUrl}}/GetReachedParticipateEvent
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}

{
"uidUser":"kebineericMuna_1668935593",
"LimitStart":0,
"LimitEnd":10


}

### Get All inputData and how user send data uid:is promotion id,

GET  {{baseUrl}}/GetParticipatedHist
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}

{
"uid":"kivuBucket_1672353285",
"uidUser":"kebineericMuna_1674160265",
"LimitStart":0,
"LimitEnd":3


}
### Get All ParticipatedHist

GET  {{baseUrl}}/GetAllParticipatedHist
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}

{
"uid":"kivuBucket_1672353285",
"uidUser":"kebineericMuna_1674160265",
"LimitStart":0,
"LimitEnd":3


}


### Quick Bonus

### GetAllQuickBonus
GET  {{baseUrl}}/GetAllQuickBonus
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}

{
"LimitStart":0,
"LimitEnd":10


}
### Search QuickBonus
GET  {{baseUrl}}/SearchQuickBonus
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}

{
"productName":"bi"



}

### SubmitQuickBonus
GET  {{baseUrl}}/SubmitQuickBonus
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}

{
"uid":"Quick_1678918381",
 "uidUser":"juma",
 "productName":"Nyota",
 "qty":"5",
 "price":"400",
 "status":"none",
 "bonusType":"Gift",
 "giftName":"PO-4",
 "giftPcs":"45",
 "bonusValue":"50",
 "totBonusValue":"60",
 "description":"gh"



}

### SubmitQuickBonus this is updatec cart Order
GET  {{baseUrl}}/UpdateSubmitQuickBonus
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}

{
 "uidUser":"juma",
 "id":"8",
 "productName":"Nyota",
 "qty":"5",
 "price":"400",
 "status":"confirm",
 "bonusType":"Gift",
 "giftName":"PO-4",
 "giftPcs":"45",
 "bonusValue":"50",
 "totBonusValue":"60",
 "description":"gh"



}

### SearchSubmitQuickBonus
GET  {{baseUrl}}/SearchSubmitQuickBonus
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}

{
 "uidUser":"juma",
 "productName":"meka"




}

### Search By uid SubmitQuickBonus
GET  {{baseUrl}}/GetUidSubmitQuickBonus
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}

{
 "uidUser":"juma",
 "productName":"nyota"




}



###Safari

###Company Safari Create
POST  {{baseUrl}}/SafariCreate
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}

{
"name":"amakarito",
"comment":"comment"


}

###Company Safari AddItem
POST  {{baseUrl}}/SafariAddItem
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}

{
"safariuid":"amakarito_47lvw_1670704037",
"uid":"Reona",
"qty":"25",
"price":"500",
"typeData":"Other",
"comment":"none"




}

###Company Safari Spent //Add Money you paid every Safari
POST  {{baseUrl}}/SafariSpent
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}

{
"numberQr":3

}

###Company Safari Spent //Add Money you paid every Safari
GET  {{baseUrl}}/SafariCalculate
content-type: application/json;charset=UTF-8
Authorization: Bearer {{Auth_token}}

{
"safariuid":"amakarito_47lvw_1670704037",
"name":"safari"

}





